### ISSUE TITLE
Develop and add a page for tutorials and case studies

### ISSUE THREAD

**Issue by nikeshbalami** [school-of-data/open-geodata-curriculum#4]
### Acceptance Criteria
- [x] I can now add the tutorials @ Curriculum website
- [x] I can now add case studies @ Curriculum website

### Tasks
- [x] Analyze the current behaviors of the curriculum page
- [x] Develop the tutorials and case studies page (taking the reference from the project showcase)
- [x] Test the page with the dummy content
- [x] Submit PR for the review

### Preferred flow
1. Tutorials
2. Case Studies
3. Project Showcases

**Comment by nikeshbalami** [comment]
@benhur07b this has been implemented via #5, please feel free to review and merge.

Just a heads up, it has dummy content so that it become easier to understand where to replace content. Feel free to replace the dummy content once you merge it :)

**Comment by nikeshbalami** [comment]
Closing this issue for now, as implementation #5 has been approved and merged.
