### ISSUE TITLE
Add "how to update" modules on website documentation

### ISSUE THREAD

**Issue by nikeshbalami** [school-of-data/open-geodata-curriculum#6]
The website documentation needs to be improved and modules on how to update Tutorials, Case Studies, and Showcase need to be added so that anyone can update content by following the documentation.

### Acceptance Criteria
- [x] I can see the modules added to the documentation

### Tasks
- [x] Go through the website documentation (https://docs.google.com/document/d/1BVppXLvNW2EnmIR7eecXcBKRcuNBBJlYcqEFj8rtSp8/edit?usp=sharing)
- [x] Create a new section
- [x] Collect the relevant screenshot
- [x] Update the content with step by step process and screenshot
- [x] Submit it for the review

**Comment by nikeshbalami** [comment]
Curriculum documentation is now updated: https://docs.google.com/document/d/1BVppXLvNW2EnmIR7eecXcBKRcuNBBJlYcqEFj8rtSp8/edit?usp=sharing
